.travis.yml
client/fixtures.py
client/tests/run_tests.sh
client/tests/test_orion_handler.py
conftest.py
experiments/grafana/docker-compose.yml
experiments/grafana/ql_feeder.py
reporter/reporter.py
reporter/tests/docker-compose.yml
reporter/tests/run_tests.sh
reporter/tests/test_reporter.py
setup_dev_env.sh
translators/crate.py
translators/fixtures.py
translators/tests/run_tests.sh

Missing datetime in a notification is no longer critical. Let's assume notification arrival time as modification time.
PR includes cleanup of fixtures.

Assuming defaut datetime

---

experiments/grafana/docker-compose.yml

Luckily as suspected, with stack deploy and volumes "not external", the volume is not re-created when existing.
I'm adding this in this compose because it's currently being used as "reference" by some people testing QL and they've requested persistence.

Add volumes to mongo and crate in Grafana experiment

---

reporter/reporter.py
reporter/tests/test_reporter.py

Avoid errors due to missing or empty body in notify requests. (which by the way can only be POSTed to)

Treat missing or empty body

---

deps.env
docker/docker-compose-dev.yml
requirements.txt
src/exceptions/exceptions.py
src/reporter/delete.py
src/reporter/query_1T1E1A.py
src/reporter/query_1T1ENA.py
src/reporter/tests/docker-compose.yml
src/reporter/tests/test_1T1E1A.py
src/reporter/tests/test_1T1ENA.py
src/reporter/tests/test_delete.py
src/reporter/tests/test_version.py
src/reporter/tests/utils.py
src/reporter/version.py
src/translators/crate.py
src/translators/tests/docker-compose.yml
src/translators/tests/test_crate.py

To let users ignore entity_type when entity_id is unique I though of using a more recent feature of crate, but in the end decided not to depend on those for now. Upgrading crate version was still worth pursuing. Same thing for Orion.

Update crate version + let users ignore entity_type

---

Pipfile
Pipfile.lock

This PR fixes #131.
Specifically there's a security vulnerability in `PyYAML` that could allow an attacker to execute arbitrary code using a YAML file. Even though we don't use `PyYAML` directly, `connextion`, one of our deps, does as does `clickclick`, a lib `connexion` depends on.
At the moment, there's no official `PyYAML` release with the fix, only pre-release versions. It seems `PyYAML` hasn't been getting much love in the last couple of years, but fortunately they're [planning to release version 4.2][pyyaml-4.2] which should include the fix for CVE-2017-18342.
Since there's no official `PyYAML 4.2`, the best we can do for the time being is to bring in a patched version through an explicit dependency in our `Pipfile`:
pyyaml = ">=4.2b1"
But this has the downside we now have to …

Fix security vulnerability CVE-2017-18342.

---

Pipfile
Pipfile.lock
specification/quantumleap.yml
src/reporter/reporter.py
src/reporter/subscription_builder.py
src/reporter/tests/test_subscribe.py
src/reporter/tests/test_subscription_builder.py
src/reporter/tests/test_time_format.py
src/reporter/tests/test_timex.py
src/reporter/timex.py
src/utils/jsondict.py
src/utils/subscription_dsl.py
src/utils/tests/test_jsondict.py
src/utils/tests/test_timestr.py
src/utils/timestr.py

This PR implements a strategy to select a time index value from the notification payload and implements the features requested in #93.
We determine which attribute or metadata value to use as a time index for the entity being notified by selecting the first value found in the below list that can be converted to a `datetime`. Items are considered from top to bottom, so that if multiple values are present and they can all be converted to `datetime`, the topmost value is chosen.
1. Custom time index. The value of the `Fiware-TimeIndex-Attribute`. Note that for a notification to contain such header, the corresponding subscription has to be created with an `httpCustom` block as detailed in the *Subscriptions* and *Custom Notifications* sections of the [NGSI spec][ngsi-spec].
2. `TimeInstant` …

Time index selection

---

docs/manuals/user/index.md
src/reporter/subscription_builder.py
src/reporter/tests/test_subscribe.py
src/reporter/tests/test_subscription_builder.py
src/reporter/tests/test_timex.py
src/reporter/timex.py

Updated <code>time_index</code> selection with three new steps (2, 5 and 6):
We determine which attribute or metadata value to use as a time index for the entity being notified by selecting the first value found in the below list that can be converted to a datetime. Items are considered from top to bottom, so that if multiple values are present and they can all be converted to datetime, the topmost value is chosen.
1. Custom time index. The value of the <code>Fiware-TimeIndex-Attribute</code>. Note that for a notification to contain such header, the corresponding subscription has to be created with an httpCustom block as detailed in the Subscriptions and Custom Notifications sections of the [NGSI spec](http://fiware.github.io/specifications/ngsiv2/stable/).
2. Custom time index metadata. …

Time_index enhancement (issue 172)

---

src/conftest.py
src/reporter/reporter.py
src/reporter/tests/test_notify.py
src/translators/crate.py
src/translators/tests/test_crate.py
src/utils/common.py

The notify API can now process notifications whose data array contains more than one element.
Previously it returned an error message with the HTTP status 400.
reporter.reporter.notify method now loops through each data element
performing the operations previously done to the single element such as adding the time index and validating.
translators.crate.CrateTranslator._preprocess_values method now adds None to the values list if an entity update doesnot have a value for a given attribute.
Before it threw a KeyError exception. This allows _insert_entities_of_type to successfully insert
entities that have different attributes.
Tests were modified to test for this new feature:
- Test data was added to conftest
- test_notify.test_no_multiple_data_elements was renamed and modified to test the …

Add support for multiple data elements in notifications

---

src/translators/crate.py
src/translators/tests/test_crate.py

While executing API {ql_ip}:{ql_port}/v2/entities/{entity_id} to get all attributes of the entity having **"null"** values for the attribute of type **"geo:point"** an error is shown as follows: 
**"Something went wrong with QL. Error: 'NoneType' object is not iterable"**.
After investigation, I have found that this error occurs because of the code which insert value of longitude and latitude with the None value.
To remove this error, I have added a check for the None value when type is NGSI_GEOPOINT.

Support for NGSI_GEOPOINT for null values

---

src/reporter/query_1T1E1A.py
src/reporter/query_1TNE1A.py
src/reporter/tests/test_attribute_name_case.py
src/translators/crate.py
src/utils/dicts.py
src/utils/tests/test_dicts.py

This PR is a fix for #206.
Call `AN` the set of all valid attribute names and consider the following equivalence relation on `AN`
x ~ y  ⟺  lower(x) = lower(y)
where `lower` is the function that converts a string to lowercase. Quantum Leap identifies an entity attribute named `x` with the corresponding equivalence class `[x]` when storing and querying the data. In detail: when an attribute named `x` gets stored for the first time, Quantum Leap stores its value in a column named `y = lower(x)` as well as the metadata pair `(original name, column name) = (x, y)`. When querying `x` attribute values, you can then specify any member of `[x]` as attribute name in the query parameters or URL. This has the obvious downside that if an entity in JSON format contains two equivalent attributes (e.g. …

Fix GH #206

---

specification/quantumleap.yml
src/reporter/query_1T1E1A.py
src/reporter/query_1T1ENA.py
src/reporter/query_1TNE1A.py
src/reporter/tests/geo_queries_fixture.py
src/reporter/tests/test_1T1E1A.py
src/reporter/tests/test_1T1ENA.py
src/reporter/tests/test_1TNE1A.py
src/reporter/tests/test_attribute_name_case.py
src/reporter/tests/test_entities_with_odd_chars.py
src/reporter/tests/test_incomplete_entities.py
src/reporter/tests/test_integration.py
src/reporter/tests/test_multitenancy.py
src/reporter/tests/test_time_format.py
src/tests/common.py

This PR implements the flattening JSON query responses as outlined in #213 and additionally changes the array type of values returned by the queries from an array of numbers to an array of any type. The reason for the latter change is that attribute values may not only be numbers, but any of the valid types permitted by the NGSI spec.
The implemented changes break API backward compatibility so it will have to be managed accordingly at API and release level---e.g. new API version, advertise change, etc.

Flatten JSON in query results

---

setup_dev_env.sh

apparently eth0 is gone in travis ci, thus we need to get the ip from another interface

fix-breaking-travis-ci

---

docker/docker-compose-dev.yml
docs/manuals/admin/configuration.md
mkdocs.yml
src/geocoding/geocoding.py
src/geocoding/tests/test_geocoding.py
src/reporter/reporter.py
src/reporter/tests/docker-compose.yml
src/translators/crate.py
src/translators/factory.py
src/translators/timescale.py
src/utils/cfgreader.py

fix #160 and introduce multiple level of logs
* differentia log levels
* add `LOGLEVEL` env variable
* document env variables

introduce support for log level configuration

---

.travis.yml
README.md
deps.env
docker/docker-compose.yml
docs/manuals/admin/index.md
src/reporter/health.py
src/reporter/tests/docker-compose.yml
src/reporter/tests/test_NTNE.py
src/reporter/tests/test_NTNENA.py
src/tests/docker-compose.yml
src/tests/run_tests.sh
src/translators/crate.py
src/translators/tests/docker-compose.yml
src/translators/tests/test_crate.py

fix #256 
@c0c0n3 three test are failing. 
* `test_NTNE_limit` probably because the query is actually wrong
* `test_NTNE_offset` may be actually a crate bug. i run the query manually and it seems that crate 4.x is not handling correctly `offset` when using it with an aggregate query (at least if in a union all select)
* `test_bc` well of course moving to crate 4.x it's not backward compatible with ql 0.5.1

support crate 4.x

---

README.md
src/translators/crate.py

Since cratedb 4.0 timestamp is deprecated and may be removed any time soon. This update, provide timestamptz support for cratedb >= 4.0

Improve crate 4.x support 

---

src/translators/sql_translator.py

#353 reported `fromDate` and `toDate` to not be working correctly. test we run using crate 4.x didn't expose the problem. still user reported the issue, so we looked into using crate 3.x (that will be deprecated in 0.8!) and have been able to reproduce the issue. while the generated timestamp (without `T`) was supported by crate 4.x, it is not the case for 3.x. we changed the timestamp to include `T`.
the issue didn't surface because of the related exception is `managed`, this should probably be modified. currently, the error is at least promoted from "debug" to "error" log, but probably the exception should be simply raised and correctly reported to api caller.
on an additional note, it is unclear why the test using old version of crate that we run on each PR didn't break.

fix date format to be compatible also with crate 3.x (#353)

---

.github/pull_request_template.md
.github/workflows/cla.yml
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
docs/manuals/user/contributing.md

This PR makes QL comply with FiWare tech committee's recent decision about contribution guidelines and CLA---see #389. Specifically we have
* updated the code of conduct (Contributor Covenant Code of Conduct 2.0)
* added a contribution guidelines doc as required by FiWare
* implemented the FiWare PR template
* enforced signing of FiWare CLA on PR submission
Notice the signing of CLA uses a GitHub action that [probably won't work][protect] out of the box for us since our `master` branch is protected. Let's see what happens after the merge, if it actually works then all the better, otherwise we'll have to come up with a workaround.
Also I've added a repo secret called `PERSONAL_ACCESS_TOKEN`---which is what the GitHub action looks for
- …

Adopt FIWARE contribution guidelines

---

docs/manuals/admin/configuration.md
src/translators/crate.py

* by enabling "write.wait_for_active_shards = 1" writes are possible also when table health is not 100%

active shards 1 crate

---

.travis.yml

* added DOCKER_PASSWORD and DOCKER_USERNAME to travis
* authenticate before launching CI tests
As discussed in https://blog.travis-ci.com/docker-rate-limits, Docker recently announced that they will be actively limiting rates for free and anonymous users in an effort to make Docker, as an organisation, as sustainable as possible.
Due to this, during last CI processes we noticed an increasing number of errors:
**Docker Hub: You have reached your pull rate limit**
ask. We're here to help! This is simply a reminder …

Fix Docker Hub pull request limit reached in Travis

---

README.md
docs/manuals/user/troubleshooting.md

Provide some background information on data availability after write
feature works
N/A

add clarifications to docs in relation to #418

---

RELEASE_NOTES.md
specification/quantumleap.yml
src/reporter/tests/test_version.py
src/reporter/version.py

With this PR, we releases QuantumLeap version `0.8.0`. This version comes with:
* Experimental support to store NGSI-LD payloads: The `notify` API endpoint now accepts both NGSI-LD and NGSI-v2 entities! While there are still some limitations to what NGSI-LD payloads QuantumLeap can process, the most common scenarios should be covered.
* Much improved data ingestion (`notify` API endpoint) performance with a brand new Redis query cache.
* Full support for Timescale: The Timescale backend is now on par, in terms of features, with the CrateDB backend---i.e. all API endpoints work both with Timescale and CrateDB. Running both backends side-by-side is also supported---e.g. routing data to a specific DB depending on tenant.
* Gunicorn support: You can now run QuantumLeap as a WSGI app in your …

Release 0.8.0

---

.gitignore
README.md
RELEASE_NOTES.md
deps.env
run_tests.sh
src/tests/common.py
src/tests/test_integration.py
src/translators/crate.py
src/translators/sql_translator.py
src/translators/tests/test_crate.py
src/translators/tests/test_insert_batches.py

Test new version of services: Orion 2.6.1, Crate 4.5.1,  Timescale 1.7.5-pg12, Redis 6.2.3.
Updates to code to support changes in Crate 4.4+
feature works
N/A
"Contributing …

updates to support crate 4.4+

---

docs/manuals/admin/crate.md
docs/manuals/user/troubleshooting.md

Added description as described in [Issue](https://github.com/orchestracities/ngsi-timeseries-api/issues/343)
feature works
- [ x ] I have added necessary documentation (if appropriate)
Added documentation as per …

Fix for Issue #343

---

run_tests.sh

fix error
CircleCI mentioned a bash syntax error in run_tests.sh (`run_tests.sh: 7: [: 0: unexpected operator` e.g. in [this job](https://app.circleci.com/pipelines/github/orchestracities/ngsi-timeseries-api/439/workflows/221b0ba3-4c3f-4348-87a7-10810119ff79/jobs/2157))
Fixed the bash syntax here.
feature works
by …

fix run_tests bash syntax error

---

Pipfile
Pipfile.lock
RELEASE_NOTES.md
src/geocoding/geocoding.py

the library geocoder is unmaintained since 4 years, so time to replace it. more, the new library supports async calls!
replace old library with new one
feature works
N/A
[contrib]: …

replace geocoder with geopy

---

.github/workflows/docker.yml
RELEASE_NOTES.md

The github action is not correctly generating tags for the docker images. e.g. instead of generating 0.8.3 tag, generated release-0.8.3, and didn't tag it also as "latest".
N/A …

fix issues with ci worfklow for docker

---

RELEASE_NOTES.md
specification/quantumleap.yml
src/reporter/tests/test_version.py
src/reporter/version.py

With this PR, we releases QuantumLeap version 1.0.0.
- Removed subscription API (#493)
- Replaced geocoder with [geopy](https://geopy.readthedocs.io/en/stable/) (#610)
- Bumped pillow from 8.4.0 to 9.0.0
- Aligned missing Fiware-servicePath behaviour with the one of Orion
Context Broker (#564). This is a breaking change! Before no value for
Fiware-servicePath was interpreted as python None, from now on, None
will be replaced with /. This affects only users that manually injected
data, since Orion, assume / when no servicePath is passed.
- Added more test cases for Aggregation (#499)
- fix translator initialization
- List Addix among adopters (#649)
- Replaced string with the constants (#650)
- Added idPattern ain query parameter (#648)
- Remove duplicate code in …

Release 1.0.0

---

RELEASE_NOTES.md
specification/quantumleap.yml
src/reporter/tests/test_version.py
src/reporter/version.py

prepare 1.0.1-dev cycle

---

RELEASE_NOTES.md
src/reporter/delete.py
src/reporter/op.py
src/reporter/query_1T1E1A.py
src/reporter/query_1T1ENA.py
src/reporter/query_1TNE1A.py
src/reporter/query_1TNENA.py
src/reporter/query_NTNE.py
src/reporter/query_NTNE1A.py
src/reporter/query_NTNENA.py
src/reporter/tests/test_1T1E1A.py
src/reporter/tests/test_1T1ENA.py
src/reporter/tests/test_1TNE1A.py
src/reporter/tests/test_1TNENA.py
src/reporter/tests/test_Headers.py
src/reporter/tests/test_NTNE.py
src/reporter/tests/test_NTNE1A.py
src/reporter/tests/test_NTNENA.py
src/reporter/tests/test_delete.py
src/reporter/tests/test_geo_queries_1t1e.py
src/reporter/tests/test_geo_query_1tne1a.py
src/reporter/tests/test_notify.py
src/reporter/tests/test_op.py

Removed 404 NOT FOUND in when no data found for query and returned 200 OK with empty set. Fix for issue #720 .
[release]: …

Fix to return OK/200 and an empty result set when no data found

---

RELEASE_NOTES.md
specification/quantumleap.yml
src/reporter/query_1T1E1A.py
src/reporter/query_1T1ENA.py
src/reporter/query_1TNE1A.py
src/reporter/query_1TNENA.py
src/reporter/query_NTNE.py
src/reporter/query_NTNE1A.py
src/reporter/query_NTNENA.py
src/reporter/tests/geo_queries_fixture.py
src/reporter/tests/test_1T1E1A.py
src/reporter/tests/test_1T1ENA.py
src/reporter/tests/test_1TNE1A.py
src/reporter/tests/test_1TNENA.py
src/reporter/tests/test_Headers.py
src/reporter/tests/test_NTNE.py
src/reporter/tests/test_NTNE1A.py
src/reporter/tests/test_NTNENA.py
src/reporter/tests/test_aggregation_different_attribute_types.py
src/reporter/tests/test_attribute_name_case.py
src/reporter/tests/test_entities_with_odd_chars.py
src/reporter/tests/test_incomplete_entities.py
src/reporter/tests/test_notify.py
src/reporter/tests/test_time_format.py
src/reporter/tests/test_timescale_types.py
src/reporter/tests/utils.py
src/tests/common.py
src/tests/test_integration.py
src/translators/tests/test_insert.py
src/translators/tests/test_timescale_insert.py

added id and type in place of entityId and entityType. Fix for issue #751
[contrib]: …

Change of the response format: added id and type in place of entityId and entityType

---

RELEASE_NOTES.md
docs/manuals/user/using.md
specification/quantumleap.yml

Mentioned service path isn't the same as Orion's. Fixed #758.
Also, updated Orion's link for multi-tenancy and fiware-correlator.
"Martel Open Source Software Individual …

Mentioned service path isn't the same as Orion's
