- client/fixtures.py
- client/tests/test_orion_handler.py
- conftest.py
- experiments/grafana/crate_feeder.py
- reporter/tests/test_reporter.py
- setup_dev_env.sh
- translators/base_translator.py
- translators/benchmark.py
- translators/crate.py
- translators/influx.py
- translators/rethink.py
- translators/tests/test_crate.py
Make CrateTranslator use one CrateDB table per entity type
> Entity table

- conftest.py
- reporter/reporter.py
- reporter/tests/test_reporter.py
- translators/base_translator.py
- translators/crate.py
- translators/tests/test_crate.py
- utils/common.py
Simple support for Arrays and StucturedValues attributes, used for example in AirQualityObserved Model.
Plus, typo fix of "geo:json"
> Support AirQualityObserved

- experiments/partitioning/test_partitioning.py
First attempt to get an impression on partitioning strategy
> Add partitioning experiment

- doc/manuals/admin/grafana.md
- doc/manuals/admin/index.md
Complete instructions to deploy QL in HA (referencing explanation in SmartSDK repo).
> Add reference to QL HA deployment instructions

- experiments/dataModels/Dockerfile
- experiments/dataModels/air_quality_observer.py
- experiments/dataModels/clear_orion.py
- experiments/dataModels/docker-compose.yml
- experiments/dataModels/locustfile.py
- experiments/dataModels/subscribe_ql.py
- experiments/dataModels/traffic_flow_observer.py
- experiments/dataModels/utils.py
Just refactoring the dataModels experiment to leverage on locust features.
> Refactor dataModels experiment to leverage on locust.io

- .dockerignore
- .travis.yml
- Dockerfile
- client/tests/run_tests.sh
- reporter/tests/run_tests.sh
- run_tests.sh
- translators/crate.py
- translators/tests/run_tests.sh
Collect and return pytest status of course!
Having seen the [build fail](https://travis-ci.org/smartsdk/ngsi-timeseries-api/builds/324643506), proceeded to fix the typo.
> Fix master

- translators/crate.py
- translators/tests/test_crate.py
> Remove index from long text columns

- doc/manuals/user/index.md
- translators/crate.py
- translators/tests/test_crate.py
> Support geo:point

- geocoding/tests/test_geocoding.py
- translators/crate.py
- translators/tests/test_crate.py
Treat entity type ISO8601 as DateTime
> Treat entity type ISO8601 as DateTime

- README.md
- client/fixtures.py
- reporter/delete.py
- reporter/fixtures.py
- reporter/query_1T1E1A.py
- reporter/query_1T1ENA.py
- reporter/reporter.py
- reporter/tests/run_tests.sh
- reporter/tests/test_1T1E1A.py
- reporter/tests/test_1T1ENA.py
- reporter/tests/test_delete.py
- reporter/tests/test_multitenancy.py
- reporter/tests/test_notify.py
- reporter/tests/test_subscribe.py
- reporter/tests/test_version.py
- reporter/version.py
- specification/quantumleap.yml
- translators/crate.py
- translators/tests/test_crate_delete.py
- Add 2 API endpoints to remove historical data
- Improve responses in general
> Add delete methods

- README.md
- deps.env
- reporter/reporter.py
- reporter/tests/test_notify.py
- run_tests.sh
- setup_dev_env.sh
- tests/test_integration.py
- translators/crate.py
Fix main issues found while updating docs:
- Fix the time_index policy.
- Correct cleanup of metadata on data deletion
- Minor doc adjustments
> Fixes various

- specification/quantumleap.yml
- src/exceptions/exceptions.py
- src/reporter/query_1TNE1A.py
- src/reporter/reporter.py
- src/reporter/tests/docker-compose.yml
- src/reporter/tests/test_1TNE1A.py
- src/reporter/tests/test_delete.py
- src/reporter/tests/test_version.py
- src/reporter/version.py
- src/translators/crate.py
- src/translators/tests/run_tests.sh
- src/translators/tests/test_crate_multientities.py
This means, endpoints:
- /types/{entityType}/attrs/{attrName}
- /types/{entityType}/attrs/{attrName}/value
> Implement query 1TNE1A

- README.md
- docs/manuals/admin/index.md
- docs/manuals/user/contributing.md
- mkdocs.yml
https://github.com/Fiware/developmentGuidelines
> Adjustments to comply with FIWARE GE guidelines

- specification/quantumleap.yml
- src/geocoding/geocache.py
- src/geocoding/geocoding.py
- src/reporter/health.py
- src/reporter/reporter.py
- src/reporter/tests/run_tests.sh
- src/reporter/tests/test_health.py
- src/translators/crate.py
> Add health endpoint

- README.md
- specification/quantumleap.yml
- src/reporter/query_1T1E1A.py
- src/reporter/query_1T1ENA.py
- src/reporter/query_1TNE1A.py
- src/reporter/reporter.py
- src/reporter/tests/test_1T1E1A.py
- src/reporter/tests/test_1T1ENA.py
- src/reporter/tests/test_1TNE1A.py
- src/translators/tests/test_crate.py
- src/utils/common.py
Signed-off-by: Tomas Aliaga <tomas.aliaga@gmail.com>
> Clarify aggrPeriod is not yet implemented

- specification/quantumleap.yml
- src/geocoding/tests/test_geocoding.py
- src/reporter/reporter.py
- src/reporter/subscription_builder.py
- src/reporter/tests/test_subscribe.py
- src/reporter/tests/test_subscription_builder.py
- src/utils/kvt.py
- src/utils/subscription_dsl.py
- src/utils/tests/test_kvt.py
> Extend supported params in /subscribe endpoint

- mkdocs.yml
> Fix edit docs link (GH #112)

- src/translators/crate.py
- src/translators/tests/test_crate.py
> Fix bug GH #115

- src/reporter/reporter.py
- src/reporter/tests/test_notify.py
- src/reporter/tests/test_validate_notification.py
@chicco785 so I've implemented the fix for #110 as you guys sketched it out there. Perhaps we should wait for @taliaga to come back from vacation before merging this into the release branch so he can have a chance to review it and tell me if he had something different in mind...just in case, you know :-)
> Accept notifications with missing attribute values (fix #110)

- Dockerfile
> optmize docker image (issue #113)

- README.md
- src/geocoding/tests/test_geocoding.py
Changes to follow [standard readme](https://github.com/RichardLitt/standard-readme) as recommended in the Contributor requirements
* Remove intro header
* Add link box
* Add ToC
* Standardize Section names
* Add license section
> Update README 

- src/geocoding/geocoding.py
- src/geocoding/tests/test_geocoding.py
This PR fixes #105 by selecting the most accurate result returned by the OSM geocoder.
> Use most accurate OSM result

- CREDITS
- README.md
- RELEASE_NOTES.md
- docs/roadmap.md
Fixes #133
Fixes #137 
Note this PR was already done in https://github.com/smartsdk/ngsi-timeseries-api/pull/151.
We just decided to change the base branch, hence the new PR.
> Add Credits and Roadmap

- RELEASE_NOTES.md
- src/utils/subscription_dsl.py
- src/utils/tests/test_subscription_dsl.py
> Fix GH#177

- docs/manuals/user/index.md
Updated document as per the QuantumLeap's behaviour
> Fix for issue #195

- Pipfile
- Pipfile.lock
- specification/quantumleap.yml
- src/reporter/tests/run_tests.sh
Update connexion version and get rid of openapi warning
> Update connexion version

- src/translators/crate.py
> Relax Crate health check

- RELEASE_NOTES.md
- src/reporter/tests/test_version.py
- src/reporter/version.py
- Relax Crate health check (#239)
- Timescale backend teething troubles (#237)
- add coverall badge (#236)
- Coverage tool integration with travis (#221)
> Release 0.7.3

- timescale-container/quantumleap-db-setup.py
> QL timescale init script may load different datasets in the same table

- specification/quantumleap.yml
- src/reporter/api.py
- src/reporter/tests/test_api.py
Fixes #217 as per the approach discussed.
> Handling of ql/v2 root endpoint

- docs/manuals/admin/dataMigration.md
- docs/manuals/admin/db-selection.md
- docs/manuals/admin/grafana.md
- docs/manuals/admin/ports.md
- docs/manuals/admin/timescale.md
- docs/manuals/index.md
- mkdocs.yml
This PR updates the manual to cater for the new Timescale backend, see #233.
> Timescale backend docs

- docs/manuals/user/index.md
Fixes issue-46
Updated the docs for inserting data into quantumleap directly
> Inserting data directly into Quantumleap

- docs/manuals.ja/admin/check.md
- docs/manuals.ja/admin/dataMigration.md
- docs/manuals.ja/admin/db-selection.md
- docs/manuals.ja/admin/grafana.md
- docs/manuals.ja/admin/ports.md
- docs/manuals.ja/admin/timescale.md
- docs/manuals.ja/index.md
- docs/manuals.ja/user/index.md
This PR updates some Japanese documents in docs/manuals.ja.
> (ja) Update Japanese documents

- specification/quantumleap.yml
- src/reporter/tests/test_Headers.py
- src/translators/crate.py
Fix for #148 
Updated quantumleap.yml for fiware-Service and fiware-ServicePath. 
Added test cases for the same.
Updated translators/crate.py for undefined variable name error.
> Fix for issue #148

- docs/manuals/admin/crate.md
The tutorial section was restructured.
> Update broken links in reference to CrateDB

- docs/manuals/admin/check.md
> Updated check.md

- docs/manuals.ja/admin/check.md
This PR updates check.md in docs/manuals.ja in sync with English document.
Thanks!
> (ja) Update hyper link in check.md (#289)

- specification/quantumleap.yml
- src/reporter/query_1TNENA.py
- src/reporter/tests/test_1TNENA.py
Fix for #119 
Updated specification/quantumleap.yml for API method call.
Added query_1TNENA.py for handling APIs.
Added test_1TNENA.py for test cases related to API
> Added implementation for /v2/types/{entityType}

- docker/docker-compose-dev.yml
- setup_dev_env.sh
- specification/quantumleap.yml
- src/reporter/query_NTNE1A.py
- src/reporter/query_NTNENA.py
- src/reporter/tests/test_NTNE1A.py
- src/reporter/tests/test_NTNENA.py
Fix for [Issue#118 ](https://github.com/smartsdk/ngsi-timeseries-api/issues/118) for Api implementation of /v2/attrs
Updated specification/quantumleap.yml for API method call.
Added query_NTNENA.py , query_NTNE1A.py for handling APIs.
Added test_NTNENA.py , test_NTNE1A.py for test cases related to API.
> API Implementation of /v2/attrs

- src/reporter/reporter.py
- src/reporter/tests/test_incomplete_entities.py
- src/reporter/tests/test_notify.py
- src/translators/crate.py
Fix for issue #224 
Updated reporter.py to discard entity if all values are Null.
Updated Crate.py to ignore attributes whose value is Null.
> Fix issue#224

- src/geocoding/factory.py
- src/reporter/health.py
- src/reporter/reporter.py
- src/translators/crate.py
- src/translators/factory.py
> Log env var values when reading it them in

- docs/manuals/admin/configuration.md
- src/translators/sql_translator.py
- src/translators/tests/test_sql_translator.py
@daminichopra I've ported your implementation of #303, i.e. the changeset in PR #319, to the new `SQLTranslator` class introduced by PR #315. If you could please review and give your blessing if everything is hunky-dory so we can ditch #319 and merge this PR instead. Again, soooo sorry for the mess!
> Port #319 changes to newly introduced sql translator class

- docs/manuals/admin/crate.md
Updated document that crateDB does not support 3D coordinates.
> Update document fix for crate.md

- src/reporter/reporter.py
To update message from quantum leap when database memory is not available with "not processed or not updated"
> Updated QL to notify when memory not available

- src/reporter/reporter.py
Fix for log entry with timestamp for [Issue](https://github.com/smartsdk/ngsi-timeseries-api/issues/348)
>  Updated Log entry with Timestamp 

- src/reporter/reporter.py
Fix for [Issue](https://github.com/smartsdk/ngsi-timeseries-api/issues/356)
> Added PID  and TID to logs

- .github/workflows/cla.yml
it seems cla worklfow is broken
feature works
> fix cla workflow

- src/reporter/health.py
fix #341
So far cache was a critical service, it should not. If fact if cache it's not working,
nothing prevent either db queries or geo queries.
feature works
"Contributing …
> changed cache check from critical to not critical (fix #341)

- experiments/ngsi-ld/docker-compose.yml
- experiments/ngsi-ld/orion-ld-test.sh
- src/app.py
* add demo test for orion-ld integration
* fix logger formatter issue due to new version of flask
feature works
it's a basic test for #394
> add demo test for orion-ld integration

- docs/manuals.ja/admin/configuration.md
- docs/manuals.ja/admin/crate.md
- docs/manuals.ja/admin/index.md
- docs/manuals.ja/user/contributing.md
- docs/manuals.ja/user/index.md
- docs/manuals.ja/user/troubleshooting.md
This PR only updates the Japanese documentation, not any source code. It would be great if you could review this PR. 
that issue.
feature works
If this is a relatively large or complex change, kick …
> (ja) Update Japanese documentation.

- README.md
Build badge was incorrect.
feature works
N/A
> update build status badge to travis-ci.com

- docs/roadmap.md
that issue.
- [ x I have signed the [CLA][cla]
feature works
N/A …
> roadmap-update-2021

- docs/manuals/admin/configuration.md
- src/cache/factory.py
- src/geocoding/factory.py
- src/reporter/tests/docker-compose.yml
- src/tests/benchmark/docker-compose.yml
- src/tests/docker-compose.yml
- src/translators/sql_translator.py
* add variable `CACHE_GEOCODING`  - `True` or `False` enable or disable caching for geocoding
* add variable `CACHE_QUERIES` - `True` or `False` enable or disable caching for queries
feature works
N/A
[contrib]: …
> cache configuration improvments

- README.md
Add adopters and linked projects section.
feature works
N/A
> Add adopters and linked projects section to README.md

- README.md
This PR updates description about NGSI Go. 
feature works
N/A
> Update description about NGSI Go

- README.md
that issue.
feature works
[cla]: …
> Update description about NGSI Go (#438)

- Pipfile
- Pipfile.lock
- src/cache/factory.py
- src/geocoding/factory.py
- src/reporter/tests/conftest.py
- src/reporter/tests/docker-compose.yml
- src/reporter/tests/embedded_server.py
- src/reporter/tests/run_tests.sh
- src/translators/timescale.py
This PR swaps out the QuantumLeap Docker image used in the reporter tests and replaces it with an embedded Flask server. This way `pytest` is able to collect coverage data about the `reporter` module which was previously not accessible since we were running QuantumLeap inside Docker. So the reported coverage for the `reporter` was nought whereas now it is properly reported. (Did I use report one too many times?)
What types of changes does your code introduce to the project: _Put an `x` in the boxes that apply_
[cla]: …
> Up Reporter test coverage

- .circleci/config.yml
- run_tests.sh
- src/geocoding/tests/run_tests.sh
- src/reporter/tests/run_tests.sh
- src/translators/tests/run_tests.sh
* make test parallel
* add coveralls support
feature works
N/A
> make test parallel

- README.md
Update ci badge to circle ci
feature works
N/A
> update ci badge to circleci

- .github/workflows/stale.yml
Improve management of PR and ISSUE
feature works
N/A
> add stale pr and issue checker

- RELEASE_NOTES.md
- specification/quantumleap.yml
- src/reporter/tests/test_version.py
- src/reporter/version.py
Release 0.8.1
feature works
N/A
> Release 0.8.1

- RELEASE_NOTES.md
- specification/quantumleap.yml
- src/reporter/tests/test_version.py
- src/reporter/version.py
> prepare 0.8.2-dev cycle

- .github/workflows/stale.yml
Avoid issues and pr to be automatic closed if stalled.
feature works
N/A
> remove automatic issue and pr closure

- README.md
Reword adopters section, fix EKZ broken image link, and add link to profirator site.
What types of changes does your code introduce to the project: 
N/A
> Update Adopters section

- RELEASE_NOTES.md
- src/translators/sql_translator.py
- src/translators/tests/test_query_caching.py
So far the assumption was that we were using multi-tenant orion (so service is never None),
thus we never tested query caching in this case.
This PR adds support for None service during query caching.
feature works
N/A
"Martel Open Source Software Individual Contributor License …
> support None service with query cache

- RELEASE_NOTES.md
- specification/quantumleap.yml
- src/reporter/tests/test_version.py
- src/reporter/version.py
Set-up for new dev-cycle
feature works
N/A
> prepare 0.8.3-dev cycle

- .circleci/config.yml
Complete the fix of #515.
Apparently, when the PR is from an external repository, circle ci does not load env variables.
So we need to use `.coveralls.yml` from the repo (so we need to check it out).
feature works
N/A
"Martel Open Source Software Individual Contributor License …
> add check out step to coveralls task

- .circleci/config.yml
- RELEASE_NOTES.md
- docs/manuals/admin/configuration.md
- src/translators/crate.py
- src/utils/cfgreader.py
Added `backoff_factor` which is used for retry interval between attempt of consecutive next try and so on
- [ x ] New feature (non-breaking change which adds functionality)
feature works
Refer …
> Issue #242

- RELEASE_NOTES.md
- specification/quantumleap.yml
- src/reporter/query_NTNE.py
- src/reporter/tests/test_NTNE.py
- src/reporter/tests/test_notify.py
- src/translators/sql_translator.py
Return a values field in /entities containing the last value
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] I have added tests that prove my fix is effective or that my
feature works
Fix for …
> Fix issue #478

- RELEASE_NOTES.md
> lint release notes doc

- RELEASE_NOTES.md
- docs/manuals/user/using.md
- src/reporter/reporter.py
- src/reporter/tests/test_notify.py
- src/reporter/timex.py
- src/utils/timestr.py
Added NGSI-LD temporal property 'modifiedAt'  and 'observedAt'
Fix for [Issue](https://github.com/orchestracities/ngsi-timeseries-api/issues/433)
- [ x ] New feature (non-breaking change which adds functionality)
feature works
If this is a …
> Fix for Issue #433

- docs/manuals/user/using.md
- src/reporter/conftest.py
- src/reporter/query.py
- src/reporter/reporter.py
- src/reporter/tests/test_notify.py
- src/reporter/tests/test_query.py
- src/reporter/timex.py
Fix #546 by providing related documentation.
feature works
N/A
> refer to ngsi-ld for sysAttrs option (fix #546)

- src/reporter/delete.py
- src/reporter/tests/test_delete.py
while using Drop table if there is more than one servicepath it will return message ("entity has more than one servicepath",244)
In case no service path is given it will drop whole table with code "204"
feature works …
> Drop table enhancement

- specification/quantumleap.yml
- src/reporter/tests/test_delete.py
The OpenAPI spec was missing some typing for the `/wq/management` api.
feature works
N/A
> Fix 0.8.2 spec

- .circleci/config.yml
- setup_dev_env.sh
- src/reporter/tests/geo_queries_fixture.py
- src/reporter/tests/run_tests.sh
- src/reporter/tests/test_1T1E1A.py
- src/reporter/tests/test_1T1ENA.py
- src/reporter/tests/test_1TNE1A.py
- src/reporter/tests/test_1TNENA.py
- src/reporter/tests/test_Headers.py
- src/reporter/tests/test_NTNE.py
- src/reporter/tests/test_NTNE1A.py
- src/reporter/tests/test_NTNENA.py
- src/reporter/tests/test_attribute_name_case.py
- src/reporter/tests/test_delete.py
- src/reporter/tests/test_entities_with_odd_chars.py
- src/reporter/tests/test_incomplete_entities.py
- src/reporter/tests/test_notify.py
- src/reporter/tests/test_op.py
- src/reporter/tests/test_sql_injection.py
- src/reporter/tests/test_time_format.py
- src/reporter/tests/test_timescale_types.py
- src/reporter/tests/utils.py
Fix tests failing due to cratedb data consolidation latency. While not being per se a bug of quantum leap,
with newly reduced resource on circle-ci, data consolidation takes a bit longer and this causes tests to fail.
feature works
N(/A
"Martel Open Source Software Individual …
> Reporter tests timing issues

- .github/pull_request_template.md
- .github/workflows/cla.yml
- CONTRIBUTING.md
Got a 404 error while trying to download the CLA, the url was using a `-` instead of a `_`.
feature works
"Martel Open …
> fix CLA url

- docs/manuals/index.md
Added description in cache backend section
feature works
- [ x ] I have added necessary documentation (if appropriate)
updated changes as per [Issue](https://github.com/orchestracities/ngsi-timeseries-api/issues/559)
[cla]: …
> updated cache doc

- .github/workflows/changelog.yml
- RELEASE_NOTES.md
- src/reporter/query_1T1E1A.py
- src/reporter/query_1T1ENA.py
- src/reporter/query_1TNE1A.py
- src/reporter/query_1TNENA.py
- src/reporter/query_NTNE1A.py
- src/reporter/query_NTNENA.py
- src/reporter/tests/test_different_types.py
- src/reporter/tests/utils.py
- src/translators/tests/test_aggregation.py
- src/translators/tests/test_delete.py
- src/translators/tests/test_insert.py
- src/translators/tests/test_multientities.py
- src/translators/tests/test_multitenancy.py
Add a workflow that ensure that each PR comes with updates in the `RELEASE_NOTES.md` file.
feature works
N/A
"Contributing to …
> add workflow to check that RELEASE_NOTES.md is updated

- RELEASE_NOTES.md
- src/reporter/query_1T1E1A.py
- src/reporter/query_1T1ENA.py
- src/reporter/query_1TNE1A.py
- src/reporter/query_1TNENA.py
- src/reporter/query_NTNE.py
- src/reporter/query_NTNE1A.py
- src/reporter/query_NTNENA.py
Added warning in response format for Fix of [Issue](https://github.com/orchestracities/ngsi-timeseries-api/issues/514)
- [ x ] New feature (non-breaking change which adds functionality)
feature works
Related to …
> Added warning in response format

- RELEASE_NOTES.md
- src/reporter/tests/test_instanceId.py
- src/translators/sql_translator.py
Added instanceId for each entry received.  Fix for issue #533 . I'll add and update the test cases once code change is accepted.
feature works
[cla]: https://raw.githubusercontent.com/orchestracities/ngsi-timeseries-api/ma …
> Added instanceId for each entry received

- .github/workflows/codeql-analysis.yml
- RELEASE_NOTES.md
Add codeql-analysis workflow
feature works
N/A
> add codeql-analysis workflow

- RELEASE_NOTES.md
- src/reporter/tests/test_aggregation_different_attribute_types.py
- src/reporter/tests/test_instanceId.py
> add wait for insert in aggregation tests

- README.md
- RELEASE_NOTES.md
- docker/docker-compose-dev.yml
- docker/docker-compose.wq.yml
- docker/docker-compose.yml
- docs/manuals/admin/benchmarks.md
- docs/manuals/admin/check.md
- docs/manuals/admin/crate.md
- docs/manuals/admin/installing.md
- docs/manuals/admin/wq.md
- docs/manuals/index.md
- docs/manuals/user/contributing.md
- docs/manuals/user/pagination.md
- docs/manuals/user/troubleshooting.md
- docs/manuals/user/using.md
- docs/roadmap.md
Improve documentation.
feature works
N/A
> revise documentation

- RELEASE_NOTES.md
- docs/roadmap.md
fix link and text in roadmap
only change in the documentation
[rel-notes]: https://github.com/smartsdk/ngsi-timeseries-api/blob/master/RELEASE_NOTES.md
> fix link and text in roadmap

- .github/pull_request_template.md
- RELEASE_NOTES.md
Update links in PR template
feature works …
> update links in pr template

- .github/pull_request_template.md
- RELEASE_NOTES.md
* Add running tests locally to PR template checklist.
* Add linting locally to PR template checklist.
* Reformat text to work around GitHub broken markdown renderer---newlines break sentences.
N/A
[release]: https://github.com/orchestracities/ngsi-timeseries-api/blob/master/RELEASE_NOTES.md
"QuantumLeap Release Notes"
> Update PR template

- .circleci/config.yml
- Pipfile
- Pipfile.lock
- README.md
- RELEASE_NOTES.md
- deps.env
- docker/docker-compose.yml
- src/reporter/tests/conftest.py
- src/reporter/tests/run_tests.sh
- src/tests/test_integration.py
- src/translators/tests/conftest.py
Update services to a new release. Unfortunately, for the last versions of timescaledb, there is not official image with postgis.
N/A
[release]: …
> update to new releases

- README.md
- RELEASE_NOTES.md
This PR updates the README to list [Addix](https://addix.net/) among QuantumLeap adopters.
N/A
[release]: …
> List Addix among adopters

- RELEASE_NOTES.md
- src/translators/sql_translator.py
fix for issue #650 
[contrib]: https://github.com/orchestracities/ngsi-timeseries-api/blob/master/CONTRIBU …
> Resolved TODO at line 44 in sql_translator.py

- RELEASE_NOTES.md
- src/reporter/tests/test_timescale_types.py
- src/translators/tests/original_data_scenarios.py
- src/translators/tests/test_insert_batches.py
- src/utils/tests/tenant.py
remove the duplicate code in src/reporter/tests/test_timescale_types.py
[contrib]: …
> Remove duplicate code mentioned at:ngsi-timeseries-api/src/reporter/tests/test_timescale_types.py

- RELEASE_NOTES.md
- src/translators/sql_translator.py
is_text method is in utils. fix for issue #659
[contrib]: …
> is_text method is in utils 

- RELEASE_NOTES.md
- src/wq/ql/notify.py
Added logs in src/wq/ql/notify.py fix for issue #656 
[contrib]: …
> Added logs for issue#656

- RELEASE_NOTES.md
- src/wq/core/task.py
Added logs in src/wq/core/task.py. fix for issue #662 
[contrib]: …
> Fix for issue#662

- RELEASE_NOTES.md
- src/reporter/query_NTNE.py
- src/reporter/query_NTNE1A.py
- src/reporter/tests/test_1TNE1A.py
- src/reporter/tests/test_1TNENA.py
- src/reporter/tests/test_NTNE.py
- src/reporter/tests/test_NTNE1A.py
- src/reporter/tests/test_NTNENA.py
- src/translators/sql_translator.py
- src/utils/tests/tenant.py
- src/wq/core/task.py
fixed for linter failures ( #670 ) 
[contrib]: …
> fix for linter failing #670

- RELEASE_NOTES.md
- src/translators/sql_translator.py
Replaced entity with getter. Fix for issued #652 
[contrib]: …
> Fixed issue 652

- Dockerfile
- RELEASE_NOTES.md
fix for broken docker image. issue #674 
[contrib]: …
> Fix for broken docker image#674

- RELEASE_NOTES.md
- timescale-container/Dockerfile
that issue.
[cla]: https://raw.githubusercontent.com/orchestracities/ngsi-timeseries-api/mas …
> Resolve TODO in Dockerfile #680

- RELEASE_NOTES.md
- src/translators/sql_translator.py
that issue.
[cla]: https://raw.githubusercontent.com/orchestracities/ngsi-timeseries-api/mas …
> Resolved TODO in sql_translator.py #683

- README.md
- RELEASE_NOTES.md
Fix broken link in README.md
[contrib]: https://github.com/orchestracities/ngsi-timeseries-api/blob/master …
> Fix for Issue 688

- RELEASE_NOTES.md
- src/translators/sql_translator.py
Resolved TODO at src/transaltors/sql_transaltor.py #694 
[contrib]: …
> Fix for issue#694

- RELEASE_NOTES.md
- src/wq/ql/notify.py
Added error handling in src/wq/ql/notify.py fix for issue #673  
[contrib]: …
> fix for issue#673

- RELEASE_NOTES.md
- docker/docker-compose-dev.yml
that issue.
[cla]: https://raw.githubusercontent.com/orchestracities/ngsi-timeseries-api/mas …
> #725 Incorrect notation in docker compose file

- RELEASE_NOTES.md
- timescale-container/crate-exporter.py
Added escaping in crate-exporter.py. Fix for #702 
[contrib]: …
> Fix for 702

- RELEASE_NOTES.md
- src/geocoding/tests/test_geocoding.py
Fixed geocoding test case. Now all test cases are passing on CircleCI. Fix for #755 .
Please find below screenshot:
"Martel Open Source Software Individual Contributor License …
> fix for 755

- .circleci/config.yml
- RELEASE_NOTES.md
Updated Ubuntu image for CircleCI. Fixed #753 .
[contrib]: …
> Updated Ubuntu image for CircleCI

- RELEASE_NOTES.md
- docker/docker-compose-common.yml
- docker/docker-compose-dev.yml
- docker/docker-compose.wq.yml
- docker/docker-compose.yml
Updated docker compose files. Fix for #598 .
[contrib]: …
> Updated docker compose files
